name: snow_fish
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database
  supabase_flutter: ^2.5.2
  supabase: ^2.2.0

  # UI & Utils
  cupertino_icons: ^1.0.6
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  lucide_icons: ^0.257.0
  photo_view: ^0.14.0

  # File upload / media
  file_picker: ^10.3.8
  video_player: ^2.5.1
  http: ^1.6.0
  dio: ^5.2.1
  image: ^4.0.17
  mime: ^1.0.2
  path: ^1.8.3
  video_thumbnail: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
